#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;
$blop->assert_csrf;

my $out = {};

my $current = $cgi->param("current") || "";
if ($current ne $blop->{conf}{pass}) {
    $out->{currentError} = "Invalid.\n";
    $out->{error} = 1;
}

my $pass = $cgi->param("pass") || "";
if (!length($pass)) {
    $out->{passError} = "Cannot be empty.\n";
    $out->{error} = 1;
}

my $confirm = $cgi->param("confirm") || "";
if ($confirm ne $pass) {
    $out->{confirmError} = "Confirmation doesn't match.\n";
    $out->{error} = 1;
}

if ($out->{error}) {
    print $blop->http_header("Content-Type" => "application/json");
    print $blop->escape_json($out);
    exit;
}

my $sth = $blop->dbh->prepare(<<EOSQL);
update config set value=? where name=?
EOSQL
$sth->execute($pass, "pass");

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({ok => 1, mesg => "Password has been changed!"});

