#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf();

if (!$blop->admin) {
    die "Admin privilege required!\n";
}

my $commentid = $cgi->param("commentid");

my $comment = $blop->comment(commentid => $commentid)
    or die "Invalid commentid.\n";

my $status = $cgi->param("status") || "";
my %args;
if ($status ne $comment->{status}) {
    $args{status} = $status;
}

if (%args) {
    my $sets = join ", ", map "$_=" . $blop->dbh->quote($args{$_}), keys %args;
    my $sth = $blop->dbh->prepare(<<EOSQL);
update comments set $sets where commentid=?
EOSQL
    $sth->execute($commentid);
}

print "Content-Type: application/json\n\n";
print $blop->escape_json({ok => 1});

