#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;
$blop->assert_csrf;

my $pageid = $cgi->param("pageid");
if (!$pageid) {
    die "A pageid is required.\n";
}

my $page = $blop->page(pageid => $pageid) or die "Invalid pageid.\n";

system "rm", "-rf", "$blop->{base}/page/$pageid";

my $sth = $blop->dbh->prepare(<<EOSQL);
delete from comments where pageid=?
EOSQL
$sth->execute($pageid);

$sth = $blop->dbh->prepare(<<EOSQL);
delete from pages where pageid=?
EOSQL
$sth->execute($pageid);

$blop->log(content => "Deleted page \"" . $page->label . "\"", pageid => $pageid);

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({
    ok => 1,
    mesg => "Deleted page $pageid.\n",
});

