#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf();

if (!$blop->admin) {
    die "Admin privilege required!\n";
}

my $pageid = $cgi->param("pageid");
if (!$pageid) {
    die "A pageid is required.\n";
}

my $name = $cgi->param("name");
if (!$name) {
    die "A file name is required.\n";
}
if ($name =~ m{(^|/)\.\.($|/)}) {
    die "Name cannot traverse upwards.\n";
}

my $file = "$blop->{base}content/page/$pageid/$name";
unlink $file;

print "Content-Type: application/json\n\n";
print $blop->escape_json({
    ok => 1,
    mesg => "Deleted $name\n",
});

