#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;
$blop->assert_csrf;

my $postid = $cgi->param("postid");
if (!$postid) {
    die "A postid is required.\n";
}

my $post = $blop->post(postid => $postid) or die "Invalid postid.\n";

system "rm", "-rf", "$blop->{base}/post/$postid";

my $sth = $blop->dbh->prepare(<<EOSQL);
delete from tags where postid=?
EOSQL
$sth->execute($postid);

$sth = $blop->dbh->prepare(<<EOSQL);
delete from comments where postid=?
EOSQL
$sth->execute($postid);

$sth = $blop->dbh->prepare(<<EOSQL);
delete from posts where postid=?
EOSQL
$sth->execute($postid);

$blop->log(content => "Deleted post \"" . $post->label . "\"", postid => $postid);

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({
    ok => 1,
    mesg => "Deleted post $postid.\n",
});

