#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;
$blop->assert_csrf;

my $categoryid = $cgi->param("categoryid");
if (!$categoryid) {
    die "A categoryid is required.\n";
}

my $category = $blop->category(categoryid => $categoryid) or die "Invalid categoryid.\n";

my $sth = $blop->dbh->prepare(<<EOSQL);
update posts set categoryid=0 where categoryid=?
EOSQL
$sth->execute($categoryid);

$sth = $blop->dbh->prepare(<<EOSQL);
delete from categories where categoryid=?
EOSQL
$sth->execute($categoryid);

$blop->log(content => "Deleted category \"" . $category->{name} . "\"", categoryid => $categoryid);

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({
    ok => 1,
    mesg => "Deleted category $categoryid.\n",
});

