#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;

my $component = $cgi->param("component") || "";
if ($component !~ /^(logo|background)$/) {
    die "Invalid component.\n";
}

for my $crud (glob "$blop->{base}content/main/$component.*") {
    unlink $crud;
}

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({ok => 1});

