#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $footer = $blop->section("footer");

print $blop->http_header();
print $blop->template("footer-section.html", footer => $footer);

