#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $footer = $blop->section("footer");

print "Content-Type: text/html; charset=utf-8\n\n";
print $blop->template("footer-edited.html", footer => $footer);

