#!/usr/bin/perl
use lib "../lib";
use blopcgi;

if (-e "$blop->{base}blop.conf") {
    die <<EOERROR;
Blop is already installed. Edit blop.conf directly if you need to work
out issues with the database or login.
EOERROR
}

my $time_zones = Blop::Date::time_zones();
$blop->{session} = undef;

print $blop->http_header();
print $blop->template("install.html", time_zones => $time_zones);
