#!/usr/bin/perl
use lib "../lib";
use blopcgi;

if (!-e "$blop->{base}blop.conf") {
    die "Blop has not been installed.\n";
}

$blop->read_conf();

print $blop->http_header();
print $blop->template("install-completed.html");

