#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();

if ($blop->session) {
    die "Please logout before logging in.\n";
}

my $redirect = $blop->escape_json_str($cgi->param("redirect") || "/admin");

print $blop->http_header();
print $blop->template("login.html", redirect => $redirect);

