#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf();

if ($blop->session) {
    die "Please logout before logging in.\n";
}

my $pass = $cgi->param("pass") || "";
if ($pass ne $blop->{conf}{pass}) {
    die "Incorrect!\n";
}

$blop->create_session();

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({ok => 1});

