#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();

if ($blop->session) {
    die "Please logout before logging in.\n";
}

my $redirect = $blop->escape_json_str($cgi->param("redirect") || "/admin");

print "Content-Type: text/html; charset=utf-8\n\n";
print $blop->template("login.html", redirect => $redirect);

