#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();

if (!$blop->session) {
    die "Not logged in.\n";
}

my $sth = $blop->dbh->prepare(<<EOSQL);
delete from sessions where sessionid=?
EOSQL
$sth->execute($cgi->cookie("sesh"));

$blop->{session} = undef;
my $cookie = $cgi->cookie(-name => "sesh", -value => "",
                          -expires => "-100d", -path => "$blop->{urlbase}/");

print $blop->http_header("Set-Cookie" => $cookie);
print $blop->template("logout.html");

