#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $limit = $cgi->param("limit");
$limit = 1000 if !defined $limit;
if ($limit !~ /^\d+$/) {
    die "Invalid limit param.\n";
}

my $offset = $cgi->param("offset");
$offset = 0 if !defined $offset;
if ($offset !~ /^\d+$/) {
    die "Invalid offset param.\n";
}

my $sth = $blop->dbh->prepare(<<EOSQL);
select sql_calc_found_rows *
from pages
order by !published, added desc
limit $limit
offset $offset
EOSQL
$sth->execute();
my @pages;
while (my $page = $sth->fetchrow_hashref()) {
    $page = bless $page, "Blop::Page";
    push @pages, $page;
}

$sth = $blop->dbh->prepare("select found_rows()");
$sth->execute();
my ($found_rows) = $sth->fetchrow_array();
my $navigation = Blop::Navigation->new($limit, $offset, $found_rows, "page");

print $blop->http_header();
print $blop->template("pages.html", pages => \@pages, navigation => $navigation);

