#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $path_info = $ENV{PATH_INFO} || "";
my ($postid) = $path_info =~ m{^/(\d+)};
my $post = $blop->post(postid => $postid) or die "Cannot find post $postid.\n";

print $blop->http_header();
print $blop->template("post-added.html", post => $post);

