#!/usr/bin/perl
use lib "../lib";
use blopcgi; 

$blop->read_conf();
$blop->require_admin();

my $post;

my $path_info = $ENV{PATH_INFO} || "";
if ($path_info =~ m{/(\d+)$}) {
    my $postid = $1;
    $post = $blop->post(postid => $postid) or die "Cannot find post $postid.\n";
}
elsif ($path_info) {
    die "Unrecognized path info.\n";
}

print "Content-Type: text/html; charset=utf-8\n\n";
print $blop->template("post.html", post => $post);

