#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $ps = $blop->section("ps");

print $blop->http_header();
print $blop->template("ps-edited.html", ps => $ps);

