#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;

my $content = $cgi->param("content");
my $name = $cgi->param("section");
my $section = $blop->section($name) or die "Invalid section.\n";

my $sth = $blop->dbh->prepare(<<EOSQL);
insert into config set name=?, value=?
on duplicate key update value=?
EOSQL
$sth->execute($name, $content, $content);

$section->{content} = $content;
$section->update_content;

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({ok => 1});

