#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf;
$blop->assert_admin;

my %args;
my $out = {};

if (diff("title")) {
    if (!$cgi->param("title")) {
        $out->{titleError} = "Please enter a title.\n";
        $out->{error} = 1;
    }
    $args{title} = $cgi->param("title");
}

if (diff("slogan")) {
    $args{slogan} = $cgi->param("slogan");
}

if (diff("email")) {
    if ($cgi->param("email") !~ /\S+\@\S+\.\S+/) {
        $out->{emailError} = "This email doesn't look right.\n";
        $out->{error} = 1;
    }
    $args{email} = $cgi->param("email");
}

if (diff("ppp")) {
    if ($cgi->param("ppp") !~ /^\d+$/) {
        $out->{pppError} = "This should be a number.\n";
        $out->{error} = 1;
    }
    $args{ppp} = $cgi->param("ppp");
}

if (diff("catlatest", "cat_latest")) {
    if ($cgi->param("catlatest") !~ /^(1|0|on|)$/) {
        $out->{catlatestError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{cat_latest} = $cgi->param("catlatest") || "";
}

if (diff("timezone")) {
    $args{timezone} = $cgi->param("timezone") || "";
}

if (diff("postcomments", "post_comments")) {
    if ($cgi->param("postcomments") !~ /^(1|0|on|)$/) {
        $out->{postcommentsError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{post_comments} = $cgi->param("postcomments") || "";
}

if (diff("pagecomments", "page_comments")) {
    if ($cgi->param("pagecomments") !~ /^(1|0|on|)$/) {
        $out->{pagecommentsError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{page_comments} = $cgi->param("pagecomments") || "";
}

if (diff("modcomments", "mod_comments")) {
    if ($cgi->param("modcomments") !~ /^(1|0|on|)$/) {
        $out->{modcommentsError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{mod_comments} = $cgi->param("modcomments") || "";
}

if (diff("gallerysmall", "gallery_small")) {
    if ($cgi->param("gallerysmall") =~ /\s+/) {
        $out->{gallerysmallError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{gallery_small} = $cgi->param("gallerysmall");
}

if (diff("gallerymedium", "gallery_medium")) {
    if ($cgi->param("gallerymedium") =~ /\s+/) {
        $out->{gallerymediumError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{gallery_medium} = $cgi->param("gallerymedium");
}

if (diff("gallerylarge", "gallery_large")) {
    if ($cgi->param("gallerylarge") =~ /\s+/) {
        $out->{gallerylargeError} = "Invalid.\n";
        $out->{error} = 1;
    }
    $args{gallery_large} = $cgi->param("gallerylarge");
}

if (diff("metadesc", "meta_description")) {
    $args{meta_description} = $cgi->param("metadesc");
}

if (diff("metatags", "meta_tags")) {
    $args{meta_tags} = $cgi->param("metatags");
}

if (diff("metaauthor", "meta_author")) {
    $args{meta_author} = $cgi->param("metaauthor");
}

if ($out->{error}) {
    print $blop->http_header("Content-Type" => "application/json");
    print $blop->escape_json($out);
    exit;
}

my $sth = $blop->dbh->prepare(<<EOSQL);
insert into config set name=?, value=? on duplicate key update value=?
EOSQL
for my $field (keys %args) {
    $sth->execute($field, $args{$field}, $args{$field});
}

print $blop->http_header("Content-Type" => "application/json");
print $blop->escape_json({ok => 1, mesg => "Settings have been updated!"});

sub diff {
    my ($field, $conf_field) = @_;
    $conf_field ||= $field;
    my $conf_value = $blop->{conf}{$conf_field} || "";
    my $cgi_value = $cgi->param($field) || "";
    return $cgi_value ne $conf_value;
}

