#!/usr/bin/perl
use lib "../lib";
use blopcgi;

$blop->read_conf();
$blop->require_admin();

my $sidebar = $blop->section("sidebar");

print $blop->http_header();
print $blop->template("sidebar.html", sidebar => $sidebar);

