#!/usr/bin/perl
use lib "../lib";
use blopcgi js => 1;

$blop->read_conf();

if (!$blop->admin) {
    die "Admin privilege required!\n";
}

my $sth = $blop->dbh->prepare(<<EOSQL);
insert into config set name=?, value=? on duplicate key update value=?
EOSQL

my $out = {};

my $allcat = $cgi->param("allcat");
$allcat = "" if !defined $allcat;
if ($allcat ne $blop->{conf}{allcat}) {
    if (!$blop->url_available($allcat)) {
        $out->{allcatError} = "Unavailable.";
        $out->{error} = 1;
    }
    else {
        $sth->execute("allcat", $allcat, $allcat);
        $blop->{conf}{allcat} = $allcat;
    }
}

my $uncat = $cgi->param("uncat");
$uncat = "" if !defined $uncat;
if ($uncat ne $blop->{conf}{uncat}) {
    if (!$blop->url_available($uncat)) {
        $out->{uncatError} = "Unavailable.";
        $out->{error} = 1;
    }
    else {
        $sth->execute("uncat", $uncat, $uncat);
        $blop->{conf}{uncat} = $uncat;
    }
}

if ($out->{error}) {
    print "Content-Type: application/json\n\n";
    print $blop->escape_json($out);
    exit;
}

print "Content-Type: application/json\n\n";
print $blop->escape_json({ok => 1});

